
# Applications list
declare -a applications=(
  "QIBM_OS400_QZBS_SVR_CENTRAL"
  "QIBM_OS400_QZBS_SVR_DATABASE"
  "QIBM_OS400_QZBS_SVR_DTAQ"
  "QIBM_OS400_QZBS_SVR_NETPRT"
  "QIBM_OS400_QZBS_SVR_RMTCMD"
  "QIBM_OS400_QZBS_SVR_SIGNON"
  "QIBM_QTV_TELNET_SERVER"
  "QIBM_OS400_QRW_SVR_DDM_DRDA"
  "QIBM_OS400_QZBS_SVR"
  "QIBM_OS400_QZBS_SVR_FILE"
  "QIBM_QSVR_OBJC_SERVER"
)
